import {
  Bakeries,
  BakeryDetail,
  BakeryOrders,
  Dashboard,
  Shops,
  ShopDetail,
  ShopOrders,
  DeliveryZoneClassification,
  DeliveryZones,
} from '../pages';
import { userPermissions } from './userPermissions';

export const AppRoutes = [
  {
    title: 'Home',
    path: '',
    component: Dashboard,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Home',
    path: 'home',
    component: Dashboard,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Bakeries',
    path: 'bakeries',
    component: Bakeries,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Bakeries Details',
    path: 'bakeries/:id',
    component: BakeryDetail,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Bakery Orders',
    path: 'bakeries/:id/orders',
    component: BakeryOrders,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Shops',
    path: 'shops',
    component: Shops,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Shop Details',
    path: 'shops/:id',
    component: ShopDetail,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Shop Orders',
    path: 'shop-orders',
    component: ShopOrders,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Delivery Zone Classification',
    path: 'shop-orders/delivery-zone-classification',
    component: DeliveryZoneClassification,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
  {
    title: 'Delivery Zones',
    path: 'delivery-zone',
    component: DeliveryZones,
    header: true,
    permissions: [...Object.values(userPermissions).map((r) => r)],
  },
];
